apiVersion: v1
kind: Secret
metadata:
  name: superset-postgresql
  namespace: "datacraftsman"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.1.6
    app.kubernetes.io/instance: superset
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "c2VINVlOektiWQ=="
  password: "c3VwZXJzZXQ="