apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-spark
  template:
    metadata:
      labels:
        app: jupyter-spark
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: jupyter
        image: quay.io/jupyter/all-spark-notebook:latest
        ports:
        - containerPort: 8888
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: jupyter-storage
          mountPath: /home/jovyan/work
      volumes:
      - name: jupyter-storage
        persistentVolumeClaim:
          claimName: jupyter-spark-pvc