apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-spark-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 10Gi