apiVersion: v1
kind: Service
metadata:
  name: jupyter-spark
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 31888  # Changed from 8888 to avoid potential conflicts
  selector:
    app: jupyter-spark