apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: email=  # base64 encoded <emailaddress>
  PGADMIN_DEFAULT_PASSWORD: password=    # base64 encoded <password>