apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  labels:
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-ceph-block