apiVersion: batch/v1
kind: Job
metadata:
  name: superset-init
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: superset-init
        image: apache/superset
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        env:
        - name: SUPERSET_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: superset-secret
              key: SUPERSET_SECRET_KEY
        command:
        - /bin/sh
        - -c
        - |
          superset fab create-admin \
            --username $(ADMIN_USERNAME) \
            --firstname $(ADMIN_FIRSTNAME) \
            --lastname $(ADMIN_LASTNAME) \
            --email $(ADMIN_EMAIL) \
            --password $(ADMIN_PASSWORD) && \
          superset db upgrade && \
          superset load_examples && \
          superset init
        envFrom:
        - secretRef:
            name: superset-secret
      restartPolicy: OnFailure