apiVersion: v1
kind: Secret
metadata:
  name: superset-secret
type: Opaque
data:
  SUPERSET_SECRET_KEY: your_secret_key_here=  # base64 encoded 'your_secret_key_here'
  ADMIN_USERNAME: admin=                            # base64 encoded 'admin'
  ADMIN_FIRSTNAME: Superset=                       # base64 encoded 'Superset'
  ADMIN_LASTNAME: Admin=                            # base64 encoded 'Admin'
  ADMIN_EMAIL: admin@superset.com=              # base64 encoded 'admin@superset.com'
  ADMIN_PASSWORD: admin=                            # base64 encoded 'admin'