apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - datacraftsman
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          regex: 'node-exporter'
          action: keep
        - source_labels: [__meta_kubernetes_node_name]
          target_label: node
        - action: labelmap
          regex: __meta_kubernetes_(.+)

      - job_name: 'cadvisor'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - datacraftsman
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          regex: 'cadvisor'
          action: keep
        - source_labels: [__meta_kubernetes_node_name]
          target_label: node
        - action: labelmap
          regex: __meta_kubernetes_(.+)