apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-role
  namespace: datacraftsman
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch