FROM python:3.11.6

RUN curl https://pyenv.run | bash

ENV PYENV_ROOT="/root.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PATH"

RUN echo 'eval "$(pyenv init --path)"' >> /root/.bashrc
RUN echo 'eval "$(pyenv init)"' >> /root/.bashrc
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> /root/.bashrc

RUN /bin/bash -c "source /root/.bashrc && pyenv install 3.11.6 && pyenv global 3.11.6"

RUN pip install mlflow boto3 virtualenv

EXPOSE 5000

CMD ["mlflow", "models", "serve," "-m", "s3://mlflow/0/1234/artificts/model/". "-h", "0.0.0.0", "-p", "5000"]