apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8098'
spec:
  type: NodePort
  ports:
    - port: 8098
      targetPort: 8098
      nodePort: 30020
  selector:
    app: cadvisor