apiVersion: v1
kind: Service
metadata:
  name: open-webui-ollama
  labels:
    helm.sh/chart: ollama-0.64.0
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui-ollama
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui-ollama