apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui-ollama
  labels:
    helm.sh/chart: ollama-0.64.0
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui-ollama
automountServiceAccountToken: true