apiVersion: v1
kind: Service
metadata:
  name: open-webui
  labels:
    helm.sh/chart: open-webui-3.6.0
    app.kubernetes.io/version: "0.3.35"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui
spec:
  selector:
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/component: open-webui
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: http
    nodePort: 30002
