apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
  namespace: default
type: Opaque
data:
  # Remember to base64 encode these values
  AWS_ACCESS_KEY_ID: <base64-encoded-access-key>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-secret-key>