apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: superset-redis
  namespace: "datacraftsman"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-17.9.4
    app.kubernetes.io/instance: superset
    app.kubernetes.io/managed-by: Helm