apiVersion: apps/v1
kind: Deployment
metadata:
  name: keepassxc
  labels:
    app: keepassxc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keepassxc
  template:
    metadata:
      labels:
        app: keepassxc
    spec:
      containers:
        - name: keepassxc
          image: lscr.io/linuxserver/keepassxc:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            seccompProfile:
              type: Unconfined
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "Etc/UTC"
          ports:
            - containerPort: 3000
              name: port-3000
            - containerPort: 3001
              name: port-3001
          volumeMounts:
            - mountPath: /config
              name: keepassxc-data
      volumes:
        - name: keepassxc-data
          persistentVolumeClaim:
            claimName: keepassxc-pvc
