apiVersion: v1
kind: Service
metadata:
  name: keepassxc-service
spec:
  type: NodePort
  selector:
    app: keepassxc
  ports:
    - name: port-3000
      port: 3000
      targetPort: 3000
      nodePort: 30000
    - name: port-3001
      port: 3001
      targetPort: 3001
      nodePort: 30001